version: "3.8"
services:
  web:
    image: mmohit1271/save-mother-nature:latest # Use the image pushed to Docker Hub
    ports:
      - "80:80" # Map port 80 on host to port 80 in container
    environment:
      - NODE_ENV=production # Set production environment
    restart: always # Ensure the container restarts on failure
